name: Build
on:
  workflow_dispatch:
jobs:
  build-base:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: docker run -v $PWD:/root/virt ubuntu:22.04 sh -c 'cd ~/virt && ./build.sh'  && tar czf kernels.tar.gz vmlinuz-amd64 vmlinuz-arm64
    - uses: actions/upload-artifact@v2
      with:
        name: kernels
        path: vmlinuz-*
